- name: '[snap] code'
  snap:
    classic: yes
    name:
      - code
- name: '[snap] chromium'
  snap:
    classic: yes
    name:
      - chromium
- name: '[snap] blender'
  snap:
    classic: yes
    name:
      - blender
- name: '[snap] krita'
  snap:
    classic: yes
    name:
      - krita