- name: 'pam_mkhomedir.so'
  pamd:
    name: common-session
    type: session
    control: required
    module_path: pam_unix.so
    module_arguments: skel=/etc/skel umask=0022
    new_type: session
    new_control: required
    new_module_path: pam_mkhomedir.so
    state: after
# - name: Desktop
#   file:
#     path: /etc/skel/Desktop
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
# - name: Documents
#   file:
#     path: /etc/skel/Documents
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
# - name: Downloads
#   file:
#     path: /etc/skel/Downloads
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
# - name: Public
#   file:
#     path: /etc/skel/Public
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
# - name: Music
#   file:
#     path: /etc/skel/Music
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
# - name: Pictures
#   file:
#     path: /etc/skel/Pictures
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
# - name: Videos
#   file:
#     path: /etc/skel/Videos
#     state: directory
#     owner: root
#     group: root
#     mode: '0755'
