- name: 'pam.d/common-session(mkhomedir)'
  copy:
    src: files/common-session
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode:  '0644'
- name: 'gdm3/custom.conf'
  copy:
    src: files/gdm3_custom.conf
    dest: /etc/gdm3/custom.conf
    owner: root
    group: root
    mode:  '0644'
- name: 'xdg/user-dirs.conf'
  copy:
    src: files/user-dirs.conf
    dest: /etc/xdg/user-dirs.conf
    owner: root
    group: root
    mode:  '0644'
- name: '/var/lib/AccountsService/users/gloria(hide from login screen)'
  copy:
    src: files/gloria
    dest: /var/lib/AccountsService/users/gloria
    owner: root
    group: root
    mode:  '0600'
- name: Desktop
  file:
    path: /etc/skel/Desktop
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Documents
  file:
    path: /etc/skel/Documents
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Downloads
  file:
    path: /etc/skel/Downloads
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Public
  file:
    path: /etc/skel/Public
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Music
  file:
    path: /etc/skel/Music
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Pictures
  file:
    path: /etc/skel/Pictures
    state: directory
    owner: root
    group: root
    mode: '0755'
- name: Videos
  file:
    path: /etc/skel/Videos
    state: directory
    owner: root
    group: root
    mode: '0755'
