---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - rpios-generic
    - rpios-services
    - basic-firewall
    - management-tools
    - desktop
    - vscode
    - vpn
    - dev-generic
    - dev-imageprocessor
    - dev-sqlite3
    - dev-ruby
    - dev-ruby-nokogiri
    - dev-ruby-sinatra
    - dev-ruby-sqlite3
    - dev-ruby-devtools
    - dev-python
    - dev-python-scipy
    - dev-python-flask
    - dev-python-matplotlib
    - dev-python-opencv
    - dev-python-pyserial
    - dev-python-sounddevice
    - dev-python-gensim
    - dev-python-sudachipy
    - fonts-bizud
    - rpios-update
