---
- hosts: rpios
  gather_facts: no
  become: yes
  roles:
    - rpios-generic
    - rpios-services
    - basic-firewall
    - management-tools
    - desktop
    - vscode
    - vpn
    - dev-generic
    - dev-imageprocessor
    - dev-sqlite3
    - dev-ruby
    - dev-ruby-nokogiri
    - dev-ruby-sinatra
    - dev-ruby-sqlite3
    - dev-python
    - dev-python-scipy
    - dev-python-flask
    - dev-python-matplotlib
    - dev-python-opencv
    - dev-python-pyserial
    - dev-python-sounddevice
    - dev-python-gensim
    - rpios-update
