- name: 'enable NetworkManager'
  copy:
    src: files/netplan_00-installer-config.yaml
    dest: /etc/netplan/00-installer-config.yaml
    owner: root
    group: root
    mode:  '0644'
- name: 'desktop & language packages'
  apt:
    force_apt_get: yes
    pkg:
      - ubuntu-desktop-minimal
      - language-pack-ja
      - language-pack-gnome-ja
      - mozc-utils-gui
      - firefox-locale-ja
      - gnome-user-docs-ja
      - ibus-mozc
      - fonts-noto-cjk-extra
      - gnome-getting-started-docs-ja
      - gnome-screenshot
      - ubuntu-gnome-default-settings
- name: 'utility packages'
  apt:
    force_apt_get: yes
    pkg:
      - emacs
      - openvpn
      - tigervnc-viewer
      - ffmpeg
      - obs-studio
      - qemu-kvm
      - vlc
      - gimp
      - inkscape
- name: 'ms teams'
  apt:
    force_apt_get: yes
    pkg:
      - teams
- name: 'libreoffice'
  apt:
    force_apt_get: yes
    pkg:
      - libreoffice
      - libreoffice-l10n-ja
- name: 'thunderbird'
  apt:
    force_apt_get: yes
    pkg:
      - thunderbird
      - thunderbird-locale-ja
- name: '[snap] code'
  snap:
    classic: yes
    name:
      - code
- name: '[snap] chromium'
  snap:
    classic: yes
    name:
      - chromium
- name: '[snap] blender'
  snap:
    classic: yes
    name:
      - blender
- name: '[snap] krita'
  snap:
    classic: yes
    name:
      - krita
- name: 'remove unuse packages'
  apt:
    force_apt_get: yes
    state: absent
    pkg:
    name:
      - gnome-initial-setup
