- name: 'keyboard pc109'
  copy:
    src: files/default_keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode:  '0644'
- name: 'desktop & language packages'
  apt:
    force_apt_get: yes
    pkg:
      - fcitx-mozc
      - mozc-utils-gui
      - fonts-noto-cjk
      - fonts-noto-color-emoji
- name: 'utility packages'
  apt:
    force_apt_get: yes
    pkg:
      - realvnc-vnc-server
      - realvnc-vnc-viewer
      - vlc
- name: 'enable vncserver-x11-serviced.service'
  systemd:
    enabled: yes
    name: vncserver-x11-serviced.service