- name: 'utility packages'
  apt:
    force_apt_get: yes
    pkg:
      - tmux
      - zsh
      - cu
      - openssh-server
- name: 'skel/tmux.conf'
  copy:
    src: files/tmux.conf
    dest: /etc/skel/.tmux.conf
    owner: root
    group: root
    mode:  '0644'
- name: 'skel/.zshrc'
  copy:
    src: files/zshrc
    dest: /etc/skel/.zshrc
    owner: root
    group: root
    mode:  '0644'
- name: 'enable ssh.service'
  systemd:
    enabled: yes
    name: ssh.service
- name: 'change Locale'
  command: raspi-config nonint do_change_locale ja_JP.UTF-8
- name: 'enable Camera'
  command: raspi-config nonint do_camera 0
- name: 'enable SPI'
  command: raspi-config nonint do_spi 0
- name: 'enable I2C'
  command: raspi-config nonint do_i2c 0
- name: 'enable Serial'
  command: raspi-config nonint do_serial 0
- name: 'GPU memory split'
  command: raspi-config nonint do_memory_split 512
