- name: 'development package(ruby)'
  apt:
    force_apt_get: yes
    pkg:
      - ruby
      - ruby-dev
      - ruby-bundler
- name: 'ruby gems(sinatra)'
  gem:
    state: latest
    user_install: no
    name: sinatra
- name: 'ruby gems(sqlite3)'
  gem:
    state: latest
    user_install: no
    name: sqlite3
- name: 'ruby gems(nokogiri)'
  gem:
    state: latest
    user_install: no
    name: nokogiri
- name: 'ruby gems(httpclient)'
  gem:
    state: latest
    user_install: no
    name: httpclient
