- name: 'texlive packages'
  apt:
    force_apt_get: yes
    pkg:
      - texlive-full
      - fonts-ipaexfont
      - evince
- name: 'texlive fonts'
  apt:
    force_apt_get: yes
    pkg:
      - fonts-ipaexfont
- name: 'texlive pdfreader'
  apt:
    force_apt_get: yes
    pkg:
      - evince
- name: 'texlive config(1)'
  command: cjk-gs-integrate --link-texmf --force
- name: 'texlive config(2)'
  command: kanji-config-updmap-sys ipaex
