-name: 'boot options'
  command: sed -i -e 's/quiet//' -e 's/splash//'  /boot/cmdline.txt
- name: 'timezone'
  file:
    src: '/usr/share/zoneinfo/Asia/Tokyo'
    dest: '/etc/localtime'
    state: link
- name: 'update cache'
  apt:
    update_cache: yes
    cache_valid_time: 10800
    force_apt_get: yes
- name: 'upgrade all'
  apt:
    name: '*'
    state: latest
    force_apt_get: yes
